version: '3'

services:
  haskell:
    container_name: 'haskell_image_gallery'
    build: .
    tty: true
    ports:
      - '3000:3000'
    command: /root/.local/bin/haskell-image-gallery-exe

  db:
    container_name: 'haskell_image_gallery_db'
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hig
      POSTGRES_PASSWORD: hig
      POSTGRES_DB: hig
