version: '3'

services:
  haskell:
    container_name: 'haskell_image_gallery'
    build: .
    tty: true
    ports:
      - "3000:3000"
  db:
   container_name: 'haskell_image_gallery_db'
   image: postgres
   restart: always
   environment:
     POSTGRES_USER: "hig"
     POSTGRES_PASSWORD: "hig"
